<?php
$migrationsDir = __DIR__ . '/database/migrations';
$files = scandir($migrationsDir);

$schemas = [
    'create_users_table' => "            \$table->id();\n            \$table->string('name');\n            \$table->string('username')->unique();\n            \$table->string('email')->unique()->nullable();\n            \$table->timestamp('email_verified_at')->nullable();\n            \$table->string('password');\n            \$table->enum('role', ['siswa', 'pembimbing_sekolah', 'pembimbing_dudi', 'pokja', 'super_admin'])->default('siswa');\n            \$table->string('avatar')->nullable();\n            \$table->boolean('is_active')->default(true);\n            \$table->timestamp('last_login_at')->nullable();\n            \$table->rememberToken();\n            \$table->timestamps();",
    'create_program_keahlians_table' => "            \$table->id();\n            \$table->string('kode')->unique();\n            \$table->string('nama');\n            \$table->timestamps();",
    'create_konsentrasi_keahlians_table' => "            \$table->id();\n            \$table->foreignId('program_keahlian_id')->constrained('program_keahlians')->cascadeOnDelete();\n            \$table->string('kode')->unique();\n            \$table->string('nama');\n            \$table->integer('durasi_pkl_bulan')->default(4);\n            \$table->date('tanggal_mulai_pkl')->nullable();\n            \$table->date('tanggal_selesai_pkl')->nullable();\n            \$table->timestamps();",
    'create_kompetensis_table' => "            \$table->id();\n            \$table->foreignId('konsentrasi_keahlian_id')->constrained('konsentrasi_keahlians')->cascadeOnDelete();\n            \$table->string('nama');\n            \$table->string('kategori')->nullable();\n            \$table->timestamps();",
    'create_dudis_table' => "            \$table->id();\n            \$table->foreignId('konsentrasi_keahlian_id')->constrained('konsentrasi_keahlians')->cascadeOnDelete();\n            \$table->string('nama');\n            \$table->text('alamat');\n            \$table->string('kota');\n            \$table->string('no_telepon')->nullable();\n            \$table->string('email')->nullable();\n            \$table->string('nama_pimpinan')->nullable();\n            \$table->string('bidang_usaha')->nullable();\n            \$table->boolean('is_active')->default(true);\n            \$table->timestamps();",
    'create_pembimbing_sekolahs_table' => "            \$table->id();\n            \$table->foreignId('user_id')->constrained('users')->cascadeOnDelete();\n            \$table->foreignId('konsentrasi_keahlian_id')->nullable()->constrained('konsentrasi_keahlians')->nullOnDelete();\n            \$table->string('nip')->nullable();\n            \$table->string('nama_lengkap');\n            \$table->string('no_hp')->nullable();\n            \$table->timestamps();",
    'create_pembimbing_dudis_table' => "            \$table->id();\n            \$table->foreignId('user_id')->constrained('users')->cascadeOnDelete();\n            \$table->foreignId('dudi_id')->constrained('dudis')->cascadeOnDelete();\n            \$table->string('nama_lengkap');\n            \$table->string('jabatan')->nullable();\n            \$table->string('no_hp')->nullable();\n            \$table->timestamps();",
    'create_siswas_table' => "            \$table->id();\n            \$table->foreignId('user_id')->constrained('users')->cascadeOnDelete();\n            \$table->foreignId('konsentrasi_keahlian_id')->constrained('konsentrasi_keahlians')->cascadeOnDelete();\n            \$table->foreignId('dudi_id')->nullable()->constrained('dudis')->nullOnDelete();\n            \$table->foreignId('pembimbing_sekolah_id')->nullable()->constrained('pembimbing_sekolahs')->nullOnDelete();\n            \$table->foreignId('pembimbing_dudi_id')->nullable()->constrained('pembimbing_dudis')->nullOnDelete();\n            \$table->string('nis')->unique();\n            \$table->string('nama_lengkap');\n            \$table->string('kelas');\n            \$table->enum('jenis_kelamin', ['L', 'P']);\n            \$table->string('no_hp')->nullable();\n            \$table->text('alamat')->nullable();\n            \$table->string('tahun_ajaran');\n            \$table->enum('status_pkl', ['belum_mulai', 'sedang_pkl', 'selesai', 'dibatalkan'])->default('belum_mulai');\n            \$table->timestamps();",
    'create_jurnals_table' => "            \$table->id();\n            \$table->foreignId('siswa_id')->constrained('siswas')->cascadeOnDelete();\n            \$table->foreignId('kompetensi_id')->nullable()->constrained('kompetensis')->nullOnDelete();\n            \$table->date('tanggal');\n            \$table->string('deskripsi_pekerjaan')->nullable();\n            \$table->text('catatan')->nullable();\n            \$table->string('foto_path')->nullable();\n            \$table->timestamps();",
    'create_absensis_table' => "            \$table->id();\n            \$table->foreignId('siswa_id')->constrained('siswas')->cascadeOnDelete();\n            \$table->date('tanggal');\n            \$table->enum('status', ['hadir', 'sakit', 'izin', 'alpha'])->default('hadir');\n            \$table->string('keterangan')->nullable();\n            \$table->time('waktu_datang')->nullable();\n            \$table->time('waktu_pulang')->nullable();\n            \$table->text('ttd_siswa_path')->nullable();\n            \$table->text('ttd_pembimbing_dudi_path')->nullable();\n            \$table->timestamps();",
    'create_laporan_pkls_table' => "            \$table->id();\n            \$table->foreignId('siswa_id')->constrained('siswas')->cascadeOnDelete();\n            \$table->string('judul');\n            \$table->text('deskripsi')->nullable();\n            \$table->string('file_path');\n            \$table->enum('status', ['draft', 'submitted', 'approved', 'rejected'])->default('draft');\n            \$table->timestamp('submitted_at')->nullable();\n            \$table->timestamps();",
    'create_buku_panduans_table' => "            \$table->id();\n            \$table->string('judul');\n            \$table->enum('tipe', ['siswa', 'dudi', 'umum']);\n            \$table->foreignId('konsentrasi_keahlian_id')->nullable()->constrained('konsentrasi_keahlians')->nullOnDelete();\n            \$table->text('deskripsi')->nullable();\n            \$table->string('file_path');\n            \$table->timestamps();",
    'create_notifikasis_table' => "            \$table->id();\n            \$table->foreignId('from_user_id')->nullable()->constrained('users')->nullOnDelete();\n            \$table->foreignId('to_user_id')->constrained('users')->cascadeOnDelete();\n            \$table->string('judul');\n            \$table->text('pesan');\n            \$table->string('tipe')->nullable();\n            \$table->boolean('is_read')->default(false);\n            \$table->timestamp('read_at')->nullable();\n            \$table->timestamps();",
    'create_monitoring_pembimbings_table' => "            \$table->id();\n            \$table->foreignId('pembimbing_sekolah_id')->constrained('pembimbing_sekolahs')->cascadeOnDelete();\n            \$table->foreignId('pokja_user_id')->constrained('users')->cascadeOnDelete();\n            \$table->date('tanggal');\n            \$table->text('catatan');\n            \$table->enum('status', ['pending', 'approved', 'rejected'])->default('pending');\n            \$table->timestamps();",
    'create_konfigurasi_sistems_table' => "            \$table->id();\n            \$table->string('key')->unique();\n            \$table->text('value')->nullable();\n            \$table->string('deskripsi')->nullable();\n            \$table->timestamps();",
    'create_activity_logs_table' => "            \$table->id();\n            \$table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();\n            \$table->string('action');\n            \$table->text('description')->nullable();\n            \$table->string('ip_address', 45)->nullable();\n            \$table->timestamps();"
];

foreach ($files as $f) {
    if ($f === '.' || $f === '..') continue;
    foreach ($schemas as $key => $schema) {
        if (strpos($f, $key) !== false) {
            $filepath = $migrationsDir . '/' . $f;
            $content = file_get_contents($filepath);
            
            if ($key === 'create_users_table') {
                $content = preg_replace('/(Schema::create\(\'users\', function \(Blueprint \$table\) \{).*?(\}\);)/s', "$1\n$schema\n        });", $content);
            } else {
                $content = preg_replace('/(Schema::create\(\'[^\']+\', function \(Blueprint \$table\) \{).*?(\}\);)/s', "$1\n$schema\n        });", $content);
            }
            file_put_contents($filepath, $content);
            echo "Updated $f\n";
            break;
        }
    }
}
?>
